[package]
name = "Hermod"
version = "0.1.0"
authors = ["Matteo Minardi <matteo.minardi2014@gmail.com"]
edition = "2021"

[workspace]
members = ["."]

[dependencies]

[[bin]]
name = "hermod"
path = "src/main.rs"